from etf_functions.XLB import xlb_attributes
from etf_functions.XLC import xlc_attributes
from etf_functions.XLE import xle_attributes
from etf_functions.XLF import xlf_attributes
from etf_functions.XLI import xli_attributes
from etf_functions.XLK import xlk_attributes
from etf_functions.XLP import xlp_attributes
from etf_functions.XLRE import xlre_attributes
from etf_functions.XLU import xlu_attributes
from etf_functions.XLV import xlv_attributes
from etf_functions.XLY import xly_attributes